### ISSUE TITLE
loop closure detection

### ISSUE THREAD

**Issue by robotdevel** [tim-fan/d435_orb_slam#1]
Hello author!

thank you so much to share great project.

I love your project it is very interesting.

it is working very well with my d435 realsense camera.

do you know how to visualize the loop closure detection?

I can not find loop closure detection topin in rviz

thank you so much about your effort!

**Comment by tim-fan** [comment]
Hi there, thanks for your message. 

Unfortunately I don't have the time to look into this, so I'm afraid I can't offer any assistance. I'd just suggest reviewing the documentation for https://github.com/appliedAI-Initiative/orb_slam_2_ros, and maybe open an issue there for further support.

Glad to hear you found this package useful!
